<?php
/**
 * Created by PhpStorm.
 * User: sebas
 * Date: 25/03/2020
 * Time: 11:52
 */

namespace App\Tests\Coin\Application\Find;


use App\Coin\Application\Create\CoinCreator;
use App\Coin\Application\Create\CoinCreatorRequest;
use App\Coin\Application\Find\CoinFinder;
use App\Coin\Domain\Coin;
use App\Coin\Domain\CoinValue;
use App\Coin\Infrastructure\Persistance\InMemoryCoinRepository;
use PHPUnit\Framework\TestCase;

class CoinFinderTest extends TestCase
{
    private $repository;

    protected function setUp()
    {
        $this->repository = new InMemoryCoinRepository();

        // Create the Coin to find in the tests
        $useCase = new CoinCreator($this->repository);
        $requestDTO = new CoinCreatorRequest('five_cents',0.05, 10);
        $useCase->create($requestDTO);


        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /** @test */
    public function foundValidCoin()
    {
        $useCase = new CoinFinder($this->repository);

        $this->assertInstanceOf(Coin::class, $useCase->find(new CoinValue(0.05)));

    }

    /** @test */
    public function throwNotValidCoin()
    {
        $this->expectExceptionMessage("not valid coin value");

        $useCase = new CoinFinder($this->repository);
        $useCase->find(new CoinValue(0.50));

    }

    /** @test */
    public function throwNotFoundCoin()
    {
        $this->expectExceptionMessage("The coin <0.25> does not exist");

        $useCase = new CoinFinder($this->repository);
        $useCase->find(new CoinValue(0.25));
    }

}