index:
    path: /product
    controller: App\Controller\Product\CreateProductPostController
    methods: [POST]

find:
    path: /product
    controller: App\Controller\Product\FindProductGetController
    methods: [GET]
