<?php
/**
 * Created by PhpStorm.
 * User: sebas
 * Date: 25/03/2020
 * Time: 13:17
 */

namespace App\Tests\Product\Application\Update;


use App\Product\Application\Create\ProductCreator;
use App\Product\Application\Create\ProductCreatorRequest;
use App\Product\Application\Update\ProductUpdateStock;
use App\Product\Domain\ProductName;
use App\Product\Domain\ProductStock;
use App\Product\Infrastructure\Persistance\InMemoryProductRepository;
use PHPUnit\Framework\TestCase;

class ProductUpdateStockTest extends TestCase
{
    private $repository;

    protected function setUp()
    {
        $this->repository = new InMemoryProductRepository();

        // Create the Product to find in the tests
        $useCase = new ProductCreator($this->repository);
        $requestDTO = new ProductCreatorRequest('water',0.65, 10);
        $useCase->create($requestDTO);


        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /** @test */
    public function updateProductStock()
    {
        $useCase = new ProductUpdateStock($this->repository);

        $useCase->update(new ProductName('water'), new ProductStock(25));

        $this->assertNull(NULL);

    }

}