<?php
/**
 * Created by PhpStorm.
 * User: sebas
 * Date: 25/03/2020
 * Time: 12:16
 */

namespace App\Tests\Coin\Application\Update;


use App\Coin\Application\Create\CoinCreator;
use App\Coin\Application\Create\CoinCreatorRequest;
use App\Coin\Application\Find\CoinFinder;
use App\Coin\Application\Update\UpdateCoinStock;
use App\Coin\Domain\CoinValue;
use App\Coin\Infrastructure\Persistance\InMemoryCoinRepository;
use PHPUnit\Framework\TestCase;

class UpdateCoinStockTest extends TestCase
{

    private $repository;

    protected function setUp()
    {
        $this->repository = new InMemoryCoinRepository();

        // Create the Coin to find in the tests
        $useCase = new CoinCreator($this->repository);
        $requestDTO = new CoinCreatorRequest('five_cents',0.05, 10);
        $useCase->create($requestDTO);


        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /** @test */
    public function increaseTheCoinStockByOne()
    {
        $coin = new UpdateCoinStock($this->repository);

        $coin->update(new CoinValue(0.05));

        $this->assertNull(NULL);

    }

}